config/routes.rb
Rails.application.routes.draw do
  root 'maps#index'
  resources :maps, except: [:new, :edit]
  resources :logistic_meshes
  wash_out :best_way
end

app/models/cost.rb
class Cost
  attr_accessor :autonomy, :gas_price, :distance
  
  def initialize
    yield self if block_given?
  end

  def calculate
    return (@gas_price * @distance) / @autonomy
  end

end

app/models/logistic_mesh.rb
class LogisticMesh < ActiveRecord::Base
  validates_presence_of :origin, :destination
  validates_numericality_of :distance
  validates_uniqueness_of :distance, scope: [:origin, :destination]
end

app/models/map.rb
class Map < ActiveRecord::Base
  validates_presence_of :name, :origin, :destination
  validates_numericality_of :autonomy, :gas_price
end

app/models/possibilities.rb
class Possibilities
  attr_accessor :origin, :destination
  def initialize
    yield self if block_given?
  end

  def check
    return "origin not found" unless LogisticMesh.where(origin: @origin).any?
    return "destination not found" unless LogisticMesh.where(destination: @destination).any?
    ways    = Hash.new {|hash, key| hash[key] = {route: [], quilometers: 0}}
    LogisticMesh.where(origin: @origin).each do |route|
      data               = ways[route.id]
      data[:route]       << route.origin
      data[:route]       << route.destination
      data[:quilometers] += route.distance
      while data[:route].last != @destination
        point = LogisticMesh.where(origin: data[:route].last).where(destination: @destination)
        if point.any?
          point = point.first
          data[:route] << point.destination
          data[:quilometers] += point.distance   
        else
          point = LogisticMesh.where(origin: data[:route].last)
          if point.any?
            point = point.first
            data[:route] << point.destination
            data[:quilometers] += point.distance   
          else
            ways.delete(route.id)
            break
          end
        end
        last_items = data[:route].last(2)
        break if last_items[0].eql?(last_items[1])
      end
    end
    ways = ways.sort_by{|k, v| v[:quilometers]}
    return ways.any? ? ways[0][1] : "route not found"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/best_way_controller.rb
class BestWayController < ApplicationController
  soap_service namespace: "levaetraz.com.br"
  soap_action 'trace_route', 
              args:   { map: :string, origin: :string, destination: :string, autonomy: :string, gas: :string }, 
              return: :string

  def trace_route
    begin
      map = Map.new({
        name:      params[:map],
        origin:    params[:origin],
        destination:   params[:destination],
        autonomy:  params[:autonomy].to_f,
        gas_price: params[:gas].to_f
      })
      if map.valid?
        possibilities = Possibilities.new do |possibility| 
          possibility.origin  = params[:origin]
          possibility.destination = params[:destination]
        end 
        best_way = possibilities.check
        if best_way.kind_of?(String)
          result = best_way
          status = 'unprocessable_entity'
        else
          cost = Cost.new do |cost|
            cost.autonomy  = params[:autonomy].to_f
            cost.gas_price = params[:gas].to_f
            cost.distance  = best_way[:quilometers].to_f
          end
          cost           = cost.calculate
          map.best_route = best_way[:route].to_sentence
          map.cost       = cost
          map.save
          result = "Best route: #{map.best_route} with cost: #{map.cost}"
          status = 'ok'
        end
        render soap: result, status: status.to_sym
      else
        render soap: map.errors.to_a.to_sentence, status: :unprocessable_entity  
      end
    rescue => e
      render soap: e, status: :unprocessable_entity
    end
  end 
end

app/controllers/logistic_meshes_controller.rb
class LogisticMeshesController < ApplicationController
  before_action :set_logistic_mesh, only: [:show, :edit, :update, :destroy]

  # GET /logistic_meshes
  # GET /logistic_meshes.json
  def index
    @logistic_meshes = LogisticMesh.all
  end

  # GET /logistic_meshes/1
  # GET /logistic_meshes/1.json
  def show
  end

  # GET /logistic_meshes/new
  def new
    @logistic_mesh = LogisticMesh.new
  end

  # GET /logistic_meshes/1/edit
  def edit
  end

  # POST /logistic_meshes
  # POST /logistic_meshes.json
  def create
    @logistic_mesh = LogisticMesh.new(logistic_mesh_params)

    respond_to do |format|
      if @logistic_mesh.save
        format.html { redirect_to @logistic_mesh, notice: 'Logistic mesh was successfully created.' }
        format.json { render :show, status: :created, location: @logistic_mesh }
      else
        format.html { render :new }
        format.json { render json: @logistic_mesh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logistic_meshes/1
  # PATCH/PUT /logistic_meshes/1.json
  def update
    respond_to do |format|
      if @logistic_mesh.update(logistic_mesh_params)
        format.html { redirect_to @logistic_mesh, notice: 'Logistic mesh was successfully updated.' }
        format.json { render :show, status: :ok, location: @logistic_mesh }
      else
        format.html { render :edit }
        format.json { render json: @logistic_mesh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logistic_meshes/1
  # DELETE /logistic_meshes/1.json
  def destroy
    @logistic_mesh.destroy
    respond_to do |format|
      format.html { redirect_to logistic_meshes_url, notice: 'Logistic mesh was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logistic_mesh
      @logistic_mesh = LogisticMesh.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logistic_mesh_params
      params.require(:logistic_mesh).permit(:origin, :destination, :distance)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :origin, :destination, :autonomy, :gas_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logistic_meshes_helper.rb
module LogisticMeshesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logistics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logistic_meshes/_form.html.erb
<%= form_for(@logistic_mesh) do |f| %>
  <% if @logistic_mesh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logistic_mesh.errors.count, "error") %> prohibited this logistic_mesh from being saved:</h2>

      <ul>
      <% @logistic_mesh.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logistic_meshes/edit.html.erb
<h1>Editing Logistic Mesh</h1>

<%= render 'form' %>

<%= link_to 'Show', @logistic_mesh %> |
<%= link_to 'Back', logistic_meshes_path %>

app/views/logistic_meshes/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Search History', root_path %>

<h1>Listing Logistic Meshes</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>destination</th>
      <th>Distance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logistic_meshes.each do |logistic_mesh| %>
      <tr>
        <td><%= logistic_mesh.origin %></td>
        <td><%= logistic_mesh.destination %></td>
        <td><%= logistic_mesh.distance %></td>
        <td><%= link_to 'Show', logistic_mesh %></td>
        <td><%= link_to 'Edit', edit_logistic_mesh_path(logistic_mesh) %></td>
        <td><%= link_to 'Destroy', logistic_mesh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logistic mesh', new_logistic_mesh_path %>

app/views/logistic_meshes/new.html.erb
<h1>New Logistic Mesh</h1>

<%= render 'form' %>

<%= link_to 'Back', logistic_meshes_path %>

app/views/logistic_meshes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @logistic_mesh.origin %>
</p>

<p>
  <strong>destination:</strong>
  <%= @logistic_mesh.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @logistic_mesh.distance %>
</p>

<%= link_to 'Edit', edit_logistic_mesh_path(@logistic_mesh) %> |
<%= link_to 'Back', logistic_meshes_path %>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :autonomy %><br>
    <%= f.text_field :autonomy %>
  </div>
  <div class="field">
    <%= f.label :gas_price %><br>
    <%= f.text_field :gas_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Logistic Meshes', logistic_meshes_path %>

<h1>Search History</h1>

<table>
  <thead>
    <tr>
      <th>Map Name</th>
      <th>Origin</th>
      <th>destination</th>
      <th>Autonomy</th>
      <th>Gas price</th>
      <th>Best Route</th>
      <th>Cost</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.origin %></td>
        <td><%= map.destination %></td>
        <td><%= map.autonomy %></td>
        <td><%= map.gas_price %></td>
        <td><%= map.best_route %></td>
        <td><%= map.cost %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @map.origin %>
</p>

<p>
  <strong>destination:</strong>
  <%= @map.destination %>
</p>

<p>
  <strong>Autonomy:</strong>
  <%= @map.autonomy %>
</p>

<p>
  <strong>Gas price:</strong>
  <%= @map.gas_price %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>